### ISSUE TITLE
Release of 0.26.0 to PyPI

### ISSUE THREAD

**Issue by halbrd** [delfick/photons#1]
Hey there, any news on when the recent changes (eg. device finder refactor) will be live on PyPI?

The latest version on PyPI is 0.25.0, and the current version on master seems to be 0.26.0: https://github.com/delfick/photons-core/blob/3aca907ff29adffcab4fc22551511c5d25b8c2b7/modules/photons_app/__init__.py#L1

I'm currently following the device_finder example, but it's changed significantly since 0.25.0.

Thanks for the library, you've made my life much easier 🙂

**Comment by Djelibeybi** [comment]
I'm seeing `0.30.0` on PyPi now, so this can probably be closed. :)

**Comment by delfick** [comment]
this is very true :)

Completely forgot about this one, too busy trying to fix the memory leak
