### ISSUE TITLE
Reset bulb

### ISSUE THREAD

**Issue by AlanW2** [delfick/photons#11]
Is there any way to have a command reset and individual bulb using its MAC address?  Manual reset by 5 power cycles is a real issue with downlights.

**Comment by delfick** [comment]
Hello,

There isn't a way to do this with the public LAN API.

I believe the reason is so it cannot be done by malicious code.

**Comment by AlanW2** [comment]
Thanks, that makes sense, but it does mean that a strategy for issue resolution is required so I will give that some thought.  Perhaps creating physical power groups that can be power cycled the requisite 5 times and then having a config that can be pushed to them would do the trick.
Perhaps having good WiFi will reduce the incidence – I don’t know why they disconnect.
I assume that reset lights can be reconfigured via Photons scripts.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by delfick** [comment]
yeap, your only option is scripting the power itself, as ugly as that is.

If you have connectivity problems, the [support team](https://lifx.typeform.com/to/LLpVPl) are really helpful there.

**Comment by AlanW2** [comment]
Yes, I have faith in support, but hopefully I won't need too much.

Sent from my Windows 10 device

**Comment by delfick** [comment]
yeah, support are great.

Anyway, because you can't reset the bulb with the LAN API I'm gonna close this issue.

Don't hesitate to make new issues with other questions!
