### ISSUE TITLE
Update lifx.yml when using Home Assistant addon

### ISSUE THREAD

**Issue by pimw1** [delfick/photons#118]
Hi,

I've been using Photons for quite a while now, and i'm very happy with it. Thank you for all the awesomeness!

I've a question: I would like to update some stuff in lifx.yml to enable hardcoded_discovery.
In the past, i was perfectly able to do so when i was running photons docker addon from a home assistant supervised installation.

Recently, i switched over to Home Asssistant OS, which is blocking access to docker volumes. Therefore, i'm now unable to update the lifx.yml.

Perhaps, for a future update, it would be cool to expose this as a confing option of home assistant. 
![image](https://user-images.githubusercontent.com/74881023/201404656-a7737bc9-78bd-4505-b4ed-b7b4778faa91.png)

Any idea/suggestion how i could manage this, would be more than welcome.

**Comment by delfick** [comment]
Hello,

that does sound like a fairly reasonable security measure they've
introduced tbh.

@Djelibeybi, do you have any ideas of what we could do here?

**Comment by Djelibeybi** [comment]
My Photons Conductor addon already does this: https://github.com/Djelibeybi/hassio-addons/tree/main/photons-interactor

I had every intention of merging my changes into this addon, but  have to admit that I completely forgot until I read this issue.

**Comment by pimw1** [comment]
Ooh wow, that would be nice!

**Comment by Djelibeybi** [comment]
To be honest, I don't use Photons Interactor these days, so my addon was slated to be archived soon. I'll try and find some time this weekend to submit a PR with the extra config bits I added.

**Comment by delfick** [comment]
that looks very cool. I actually have time to have a look this weekend.
I'll see if I can steal from you and replace my photons hassio plugin with
this s6 thing you got going here.

**Comment by delfick** [comment]
well that was pain and I gave up on having prebuilt images cause the thing that is recommended to build hassio addons is [beyond me](https://github.com/home-assistant/builder/issues/159) and making an addon for hassio is not the friendliest of activities.

But I have updated https://github.com/delfick/photons-homeassistant such that it will build the docker image on installation and allow you to put lifx.yml in the shared config folder

So doing something like using the samba plugin to get access to config and then placing a `photons/lifx.yml` in there. Do tell me if that works @pimw1

**Comment by pimw1** [comment]
Thank you! The build seemed to be stuck at first, possibly because i did not create a ` photons/lifx.yml` file first? After doing that, the build did start correctly, and i can see from the logs that it did use my lifx.yml file. After playing a bit (rebuilding -> start , rebuilding ->  start), i did got stuck again during building (it never finishes). Restarting home assistant + supervisor did the trick, and i saw that it actually was actually build and started.

So, the building of the image seems a bit buggy. But the good overall news is: once its running, it's running as expected.

**Comment by Djelibeybi** [comment]
Don't leave the web page while it's building: if you do, the Supervisor cancels the build.

**Comment by delfick** [comment]
I blame homeassistant on that. Perhaps it's more that it takes longer than
you expect?

It doesn't need the file to exist to work (well, it didn't when I tried it)

Glad you got it to work!

**Comment by delfick** [comment]
also, you don't need to rebuild if you change lifx.yml, only need to
restart it.

**Comment by pimw1** [comment]
Aah good to know! And yes, it might be that the build just takes long to build.
