### ISSUE TITLE
Add new products to registry

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#128]
The upstream product registry just got updated with the latest outdoor and other devices so it would be super peachy keen if Photons' registry were updated accordingly.

I'd do it myself but I'm not entirely sure what LCM generation some/all of these devices are, which makes adding them somewhat problematic.

Also, there is an error with two of the product definitions for which I've opened an upstreanm issue: https://github.com/LIFX/products/issues/30 -- I have manually updated my equivalent PR for `aiolifx` accordingly but I can understand waiting until upstream fix the issue before merging the change.

**Comment by delfick** [comment]
I feel that making public photons have the lcm info despite it not actually
being public info was probably not what I should have done. Lets make an
LCMX and put future products under that rather than trying to make public
photons actually want/need to know that level of detail.

**Comment by Djelibeybi** [comment]
Sounds like a reasonable plan. Do you want to do that or should I?

Aside: is/was there a way to generate the registry automatically/programatically from the `products.json` file? There is for `aiolifx` and I could've sworn there was for Photons too, but now I can't find it, so 🤷🏻‍♂️

**Comment by delfick** [comment]
I'll let you create the PR :)

If I remember correctly, the way I used to generate Photons product
registry required the internal project that had all the information, so
public photons registry is now a manual thing

I never got around to making a products version of how public photons
generates the messages.

**Comment by Djelibeybi** [comment]
Creating it automatically would be a lot simpler if we replaced the array key with something like the `pid` instead of the LCM string, but I'm unsure if that would break anything significantly. 

Given the fact that new LIFX devices are coming out in a steady stream now, it makes more sense to me to spend a bit of time creating an generator script instead of manually adding the new products.

I'm happy to take a stab at that, but I already know you'll do it quicker, more elegantly and with way more Pythonic code. 😉

**Comment by delfick** [comment]
I reckon it'd only be quicker if I had time to make such a thing. Given I
don't, I imagine your efforts would be quicker in overall terms!

**Comment by Djelibeybi** [comment]
Fair enough. I'll give it a whirl over the next couple of days as time permits.

**Comment by Djelibeybi** [comment]
> ~Fair enough. I'll give it a whirl over the next couple of days as time permits.~

This week was and next week will be a write-off because of various physical health issues and such, so I'm not going to get to this for a few weeks at least.

**Comment by delfick** [comment]
all good, this project lives in a state of negative time pressure

**Comment by Djelibeybi** [comment]
> all good, this project lives in a state of negative time pressure

If it weren't for last minute panic, I'd never get anything done.
