### ISSUE TITLE
Error when attempting to run Pacman effect

### ISSUE THREAD

**Issue by MyEyesHaveSeen** [delfick/photons#20]
I just got a second set of Tiles, set them up and stacked them on top of the first set, resulting in two parallel horizontal lines. When I attempt to run the Pacman effect, I get an TypeError: 'float' object cannot be interpreted as an integer. Previously, with one set of Tiles, the effect ran without issue.

**Comment by delfick** [comment]
Ok, are you able to run this command and give me the results:

```lifx lan:get_device_chain --silent```

And I'll see if I can replicate it

**Comment by delfick** [comment]
actually, I should have tried to run it first, the same thing happens on my tiles already!

**Comment by MyEyesHaveSeen** [comment]
So do you want to see the results of the command you asked me to run?



“Wise men speak because they have something to say; Fools because they have to say something.” -Plato

**Comment by MyEyesHaveSeen** [comment]
just a heads up, I get the same error when attempting to run Marquee

**Comment by delfick** [comment]
yeah, I should have enough information.

Marquee is essentially the same code so it makes sense that'd be broken too

**Comment by delfick** [comment]
That literally took me a minute to figure out lol

**Comment by delfick** [comment]
I have released 0.30.3 with this fix :)

**Comment by MyEyesHaveSeen** [comment]
Awesome. Now I have to see if I can remember the command to update... feel free to tell me.

**Comment by delfick** [comment]
When you've activated your virtualenv

```pip install lifx-photons-core -U``` 

:)

**Comment by MyEyesHaveSeen** [comment]
Thanks again Brother

**Comment by delfick** [comment]
You're welcome!

**Comment by MyEyesHaveSeen** [comment]
Got one more for ya, wherein my playlist used to end and go back to the command line,  I’m suddenly seeing this

**Comment by delfick** [comment]
I feel that reply is incomplete, either way, please make a new issue for it :)
