### ISSUE TITLE
Add HEALTHCHECK to Photons Interactor image

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#23]
It would be super peachy keen if the Interactor container image had [a `HEALTHCHECK` directive](https://docs.docker.com/engine/reference/builder/#healthcheck). Usually I would suggest a `curl`-based command to check the `status` of Interactor, but you don't include `curl` in the base image. I shall thus leave it up to your discretion whether to add `curl` or code something yourself. I have a bet in my head about which way you'll go with this. :)

**Comment by delfick** [comment]
we could make a python script that uses urllib to make a help request to the interactor

**Comment by Djelibeybi** [comment]
And I just won the bet in my head! :)

**Comment by delfick** [comment]
:p

**Comment by Djelibeybi** [comment]
Note that HEALTHCHECK stores the first 4096 bytes of the response on `stderr` or `stdout` and that can be seen via `docker inspect`. If you want to be fancy, a count of lights online would be nifty for the healthy output.

**Comment by delfick** [comment]
but then you're relying on the network too, probs best to just test that the interactor works

**Comment by Djelibeybi** [comment]
Would the `status` command be quicker? I'm thinking about overall impact on resource usage, given that the Photons container is fairly CPU hungry (relatively speaking).

**Comment by delfick** [comment]
oh, there's a status too. I didn't look, I like it when I think of things when I'm making the code :)
