### ISSUE TITLE
Tune the discovery timing values for standard wifi settings

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#26]
[Originally discussed on the LIFX Community Forum](https://community.lifx.com/t/add-http-api-product-identifiers-to-products-json/7203/29).

As per that discussion:

> The way discovery works in Photons is something like
> 
>  * broadcast GetService
>  * If I get no responses then retry the broadcast after a period of time (starts at 0.2 seconds and slowly increases till their 1 seconds apart)
>  * If I get any responses, then keep waiting until it’s been 0.4 seconds since the last response and assume all the collected results are everything
> 
> And also if I have any responses and I’m still waiting for that 0.4 second gap when overall timeout passes, then wait past the overall timeout till that gap has happened.

To which I replied: 

> ... the beacon interval is 100ms and the DTIM period most often recommended for most APs is 3, so devices that are sleeping only wake up every 300ms so they only have 100ms left to respond to your broadcast before the timeout occurs. 

This issue is to track tuning these values to see if we can scientifically determine a better set of defaults to discover devices that are sleeping.

**Comment by delfick** [comment]
so, the 20 seconds timeout you asked about is relevant when there aren't any devices on the network at all and it waits up to 20 seconds for any to show up.

I try to keep the timeouts as small as possible to reduce waiting.

So the higher that gap is, the longer the minimum wait for discovery to return.

You have a better setup than me to test this though given you have so many lights and I assume much more of a house than a one bedroom apartment :)

Also, I just realised I pointed you at the wrong number

it's using 350ms, https://github.com/delfick/photons/blob/main/modules/photons_transport/retry_options.py#L46

Change that number and run `lifx lan:find_devices` and see what happens is probably a good start

**Comment by Djelibeybi** [comment]
Raising the values by 0.1 each, i.e. `finish_multi_gap = 0.5` and `gap_between_results = 0.45` improves the amount of result significantly, i.e. each run is far closer to the real total of 54 than the previous values. However, it's still not completely reliable, i.e. I'm still seeing a return of 53 devices (and in one run, just 45).

Which I think proves that there is some tuning to be done, but that my method(s) are not scientific enough. I'm off to find a lab coat and some beakers and a bunsen burner and then I'm going to try some science.

**Comment by delfick** [comment]
science!

I had another look. Both are relevant, but the difference is super subtle
and a bit weird. I'll write a description later but just make it so both
are the same in your tests

**Comment by Djelibeybi** [comment]
> science!

It works, bitches! 😛 

> I'll write a description later but just make it so both are the same in your tests

Colour me intrigued. I shall add this to the science later. We're likely going to have to compromise anyway because once I get above around 0.5, the difference in how long discovery takes is very noticeable. Though, I must remember to tweak my broadcast mask because while I run a `/22` network, the LIFX bulbs are limited to a `/24`.

**Comment by delfick** [comment]
Here's an explanation of those two properties and how photons does retries and getting results https://gist.github.com/delfick/9fad819227d793d28aca49f5e52e9759

I'm not sure if it's comprehensible :p

**Comment by Djelibeybi** [comment]
I _think_ I get _most_ of it. :)

**Comment by delfick** [comment]
hehhee, which part isn't 100%?

**Comment by Djelibeybi** [comment]
Nah, I actually do get it. I just haven't bothered doing the math yet. Math is hard.

**Comment by delfick** [comment]
s/hard/impossible/

**Comment by Djelibeybi** [comment]
I meant to post this 10 days ago, but obviously actually hitting the "Comment" button was far too much effort. 😂 The reason discovery timing is interesting is because of [Unscheduled Automatic Power Save Delivery](https://en.wikipedia.org/wiki/IEEE_802.11e-2005#APSD) (or U-APSD).

However, on reflection it's probably a better idea to suggest that LIFX document that UAPSD be _disabled_ for the SSID to which the bulbs connect rather than try and adjust discovery timing to match the DTIM intervals when a device needs to come out of unscheduled sleep.

**Comment by delfick** [comment]
oh yeah, cool. Does disabling that for you made a difference?

**Comment by delfick** [comment]
So what I've done is made the gap 0.4 seconds and then made it also configurable - https://photons.delfick.com/configuration/index.html#targets

**Comment by Djelibeybi** [comment]
> Does disabling that for you made a difference?

Results are ambiguous. I need to do a more isolated test, but it's challenging to schedule with my husband (who gets cranky when his office lights go off or stop responding) working from home. :)

**Comment by delfick** [comment]
heheheh :)
