### ISSUE TITLE
Tile Arranger giving 404 and nothing loading on web UI

### ISSUE THREAD

**Issue by MetalTurtle18** [delfick/photons#44]
When running the command `lifx lan:arrange` the web UI opens, but nothing is shown and the console logs 404. I have tried on multiple browsers.

**Comment by delfick** [comment]
hmm, oops, sorry I broke it!

I changed how I build and release the arranger the last time I released it and then apparently didn't test it with the released package because it doesn't include the javascript. I'll get onto fixing that :)

**Comment by delfick** [comment]
I decided to manually release 0.5.10 with the javascript included and I'll do it properly and add javascript generation to the github action later.

It should work now :)

**Comment by MetalTurtle18** [comment]
Thanks, It works!

**Comment by delfick** [comment]
:)

**Comment by delfick** [comment]
I've finally fixed this [properly](https://github.com/delfick/photons/commit/32804cc7bc050552b225249264b8a336aa399e38). Thanks again for pointing out the problem :)

**Comment by Djelibeybi** [comment]
I'm not sure this did fix it, or perhaps you haven't pushed it to PyPi? I just installed 0.5.10 and I'm getting a blank browser window.

**Comment by delfick** [comment]
I didn't push a new version today and 0.5.10 works for me.

**Comment by Djelibeybi** [comment]
I suspect venv weirdness. It's late and I'll play with it again tomorrow and see how I broke it. 😂

**Comment by delfick** [comment]
:)
