### ISSUE TITLE
Syntax mismatch between animate help text and parameter order

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#52]
The help text for `lan:animate` states:

```
Target particular devices::

    lifx lan:animate balls match:label=wall
```

When I try to run an almost identical command, I get an error:

```bash
$ lifx lan:animate balls match:cap=matrix
...
Something went wrong! -- PhotonsAppError
	"Tried to treat a string as a serial but it wasn't valid hex"	error="Error: Odd-length string"	wanted=balls
```

If I swap the order of the matcher and animation name, I get the error from issue #51 .

**Comment by delfick** [comment]
I need to make reference on that task more lenient it seems

The new code it uses has more thorough validation than before.

And this task is special and is meant to let you swap artifact and
reference because it's less annoying for this task
