### ISSUE TITLE
Enhancement request: increase the usefulness of Interactor's logging

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#54]
Currently, Interactor's logs have limited usefulness. The only real information provided is the IP address of the requester and the how long it took to process the request. The logs also include the container health check, i.e. an extraneous piece of information every 30 seconds.

It would be super peachy keen if the logs included the actual Interactor command that was run for all commands _except_ the `status` command, for which all logging should be suppressed.

**Comment by delfick** [comment]
something like https://github.com/delfick/photons/commit/06d5c6da91eb0f4a0299974f3ab41143060f5c6e ?

This should be fine, I can't think of anything sensitive that would be logged because of that.

I'll do this in a way that's less hacky when I have time.

**Comment by Djelibeybi** [comment]
That looks good. The only missing piece of info that would be useful is the IP address of the requestor.

**Comment by Djelibeybi** [comment]
Closed via #56
