### ISSUE TITLE
Animations Don't respect brightness set

### ISSUE THREAD

**Issue by Final-Hawk** [delfick/photons#57]
Hi, 
When running animations they seem to be stuck at 100% brightness. This is the command i am running to the interactor:

```{"command":"animation/start", "args":{"matcher":{"label":"Tiles"},"animations": "pacman","transform": {"power": "on", "brightness": 0.5}}}```

To my understanding this would turn the tiles on to 50% brightness then run the pacman animation, however the tiles go to 100% when running the animation.

Hopefully its user error,
Thanks!

**Comment by delfick** [comment]
That's cause those ones are hard coded and don't have anything that changes that https://github.com/delfick/photons/blob/main/modules/photons_canvas/animations/registered/pacman.py#L19

I'm not sure I have time at the moment to play with tile animations unfortunately.

**Comment by Final-Hawk** [comment]
Makes sense. 

All good, more just wanted to see if I was doing something wrong. Thanks!

**Comment by delfick** [comment]
:)
