### ISSUE TITLE
Add options to effects/stop

### ISSUE THREAD

**Issue by delfick** [delfick/photons#64]
As pointed out in #61, Need to add to effects/stop options so you can pass things like power_on to the SetTileEffect and SetZonesEffect objects it uses

**Comment by Djelibeybi** [comment]
From what I can tell, `power_on` is about the only useful option for `effects/stop`? Would it not be easier just to add that as a boolean option?

**Comment by Djelibeybi** [comment]
Though, having a `power_off` option for `effects/stop` would be rather useful too, I reckon.

**Comment by delfick** [comment]
yeah, atm power_on is only useful one probably. But for consistency it's probs better to have matrix_options and linear_options for effects/stop too.

**Comment by delfick** [comment]
tests for now can probably just care about power_on.

We can add power_off as it's own separate option for sure, that'd be easy.

**Comment by Djelibeybi** [comment]
I just noticed that `effects/stop` can send an `apply_theme` and `power_on` is part of `theme_options`.
