### ISSUE TITLE
RPI 3b+ crashes when running Photons

### ISSUE THREAD

**Issue by Jackroser123** [delfick/photons#66]
When I installed the Photons addon into my Home assistant, it kept crashing and restarting the Raspberry Pi. I don't know exactly what the issue is, but I think that it could be due to excess CPU or memory usage. Also when it crashes, nothing is running on Photons. I have been using a Raspberry Pi 3b+ with a fan using the official power supply for running my Home assistant. Thanks.

**Comment by delfick** [comment]
Well that's bizarre. I have no idea what would cause that or really how you'd debug. It's very unlikely it's excess CPU or memory usage. 

If you run `docker stats` while you wait for it to crash, do you see it tell you about an unusual amount of resource usage?

**Comment by Jackroser123** [comment]
Hi! Thanks for your help.

I cannot run that command because I am using HASSOS, (homeassistant os). Here are the stats I can get from portainer though. Nothing is running though photons. This is not the crashing stats, its quite hard to capture since it happens at random but I will report back if I can capture it.

![unknown](https://user-images.githubusercontent.com/67406707/123890522-afa5c600-d99a-11eb-9f33-1ca0ee1e8ad5.png)

**Comment by Jackroser123** [comment]
Hmm, it seems I had 2 instances of photons running. I have removed the 2nd one and hopefully that fixes it.

**Comment by delfick** [comment]
I'm gonna close this issue. Feel free to reopen if you're still seeing problems.
