### ISSUE TITLE
Add tasks to manage Infrared and HEV lights

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#67]
If @delfick doesn't implement this in 20 minutes, I'll do it when I add cleaning as option to my DayDuysk scheduler.

Edited because Photons doesn't have distinct infrared control either.

**Comment by delfick** [comment]
I won't have time to even look at this till next week :)

**Comment by Djelibeybi** [comment]
And I'm waiting for my third bulb to arrive before I start. The most boring race in the world starts now! ;)

**Comment by delfick** [comment]
hehehehe

**Comment by Djelibeybi** [comment]
Here are my proposed task inputs/responses for HEV support. I figured it would be better to work this out _before_ implementation. 😁 

## HEV operational tasks

* `set_hev_cycle`: Start or stop an HEV cycle on the device.
* `get_hev_cycle`: Get the current state of the HEV LEDs on the device

### Operational parameters

The `set_hev_cycle` task takes two input parameters, `enabled` (boolean, required)
and `duration` (integer, optional). The `duration` field specifies the number of
seconds for the HEV cycle. If `duration` is `0` or unspecified, the default
duration will be used.

```json
{
  "enable": "[enable]",
  "duration": "[duration_s]"
}
```

### Operational response

The `get_hev_cycle` task returns the following JSON output:

```json
{
  "cycle_time_total": "[duration_s]",
  "cycle_time_left": "[remaining_s]",
  "cycle_power": "[last_power]"
}
```

## HEV configuration tasks

* `set_hev_cycle_config`: Modifies the default configuration for the HEV LEDs on the device.
* `get_hev_cycle_config`: Returns the default configuration for the HEV LEDs on the device.

### Set default configuration

The `set_hev_cycle_config` task takes two input parameters, `indication` (boolean)
and `duration` (integer). Both fields are optional. If a field is unset, the
current value will remain unchanged.

Set `indication` to `true` to run a short flashing indication at the end
of an HEV cycle.

Set `duration` to the period in seconds an HEV cycle will run when a `set_hev_cycle`
task's `duration` parameter is either `0` or unspecified.

The following example will enable the indicator and set the default cycle length
to 2 hours (7200 seconds).

```json
{
  "indication": true,
  "duration": 7200
}
```

### Get default configuration

The `get_hev_cycle_configuration` task returns the following JSON:

```json
{
  "indication": "[indication]",
  "duration": "[duration_s]"
}
```

## Results from the last HEV cycle

* `get_hev_last_cycle_result`: Returns the success/interruption result of the last HEV cycle

### Cycle has never run

```json
{
  "running": "never"
}
```

### Cycle still in progress

```json
{
  "running": true
}
```

### Cycle was successful

```json
{
  "running": false,
  "success": true
}
```

### Cycle was interrupted

The `reason` field will be one of `[ reset | homekit | lan | cloud ]`.

```json
{
  "running": false,
  "success": false,
  "reason": "homekit"
}
```

**Comment by delfick** [comment]
This all looks perfectly reasonable :)

**Comment by Djelibeybi** [comment]
Groovy. Considering we're in lockdown again, I may take a crack at it over the weekend, see how I go. I don't think I've created completely new tasks before.

**Comment by delfick** [comment]
Gotta make the most of a bad situation!

I spent the last two weeks making way too much code for work and I'll try
my best to do something else instead hahahaha

Though I'll definitely review and offer advice if you have questions :)

**Comment by Djelibeybi** [comment]
I'm now pondering just adding commands to interactor because I can control both HEV and IR with the `attr` task on the CLI. I really just need to make a simpler Interactor command so I can control it from HomeKit. :)

**Comment by delfick** [comment]
I'd say do interactor first and then add cli commands if you feel like it
just to have a play with what that looks like :)

the bulk of the change is very similar in both cases.

**Comment by Djelibeybi** [comment]
Right. From my initial jiggery-pokery, I'm going to need some helper classes in Photons anyway, so I might as well expose them as tasks. But instead of the packet oriented stuff above it'll be more like `clean/start`, `clean/stop`, `clean/status`, etc.

**Comment by delfick** [comment]
nice :)

I'd say add a file to the photons_control module for clean stuff

**Comment by Djelibeybi** [comment]
Yeah, that's where `clean.py` has been created.  I'm now working out `a_plan()` and friends.

Your code really is very, very elegant now that I understand the ... dialect, for want of a better word. I didn't know enough about Python when I first started hacking on Photons to realise that. Now that I know _just_ slightly more, it's very apparent.

**Comment by delfick** [comment]
Thanks!

**Comment by Djelibeybi** [comment]
On the hand, it does have a learning curve because the Python is ... dense. But overall, I'm really enjoying it. Can't wait for scheduling support. 😛

**Comment by delfick** [comment]
I certainly will have some time over the next couple weeks to play some more with that :)

**Comment by Djelibeybi** [comment]
Yay. 

In other news `lifx lan:clean_cycle -- '{"enable": true}'` (and `false`) works now.

**Comment by delfick** [comment]
hell yeah!

**Comment by Djelibeybi** [comment]
For anyone playing at home, `lifx lan:clean_status` works. Which means it's time to write some tests. Which means it's time to have a nice lie-down and maybe a biscuit first.

**Comment by delfick** [comment]
only one biscuit?

**Comment by Djelibeybi** [comment]
It's a very large biscuit.

**Comment by Djelibeybi** [comment]
This has been released, so why don't we all have a biscuit and close the issue?

**Comment by delfick** [comment]
![cookies](https://user-images.githubusercontent.com/109301/137620053-b9d6344e-8dcf-455d-86f3-5387e6c4f8e8.jpeg)
