### ISSUE TITLE
[interactor] Making scene doesn't work on candles

### ISSUE THREAD

**Issue by delfick** [delfick/photons#70]
As reported in https://github.com/delfick/photons/issues/61, creating a scene on a candle records a single colour instead of the matrix of zones.

**Comment by delfick** [comment]
@pimw1 I'm pushing out this [fix](https://github.com/delfick/photons/commit/daa092f2496c874af6ee7783b45bd4f81d0b4d2a) and when https://github.com/delfick/photons/runs/3331419646?check_suite_focus=true is done I'll push out the change to the homeassistant plugin and let you know.

**Comment by delfick** [comment]
@pimw1 homeassistant should have the update now to go into version 0.9.1 and then it should work. Do reopen this issue if it doesn't.

**Comment by pimw1** [comment]
Thank you delfick! I'll check it next week.

**Comment by delfick** [comment]
Try adding an `"overrides": {"duration": 2}` to the args.

**Comment by delfick** [comment]
Documentation is not one of my strong suits hahahah (and also the nature of how this project came to be meant the priority is more about doing something for enjoyment).

So essentially the best place becomes the source code or just living in my head :p 

There will hopefully come a point next year where I've had the chance to properly recover from a truly horrible two years and I can put more time into photons again and continue to work towards improving these things.

**Comment by delfick** [comment]
thanks :)

**Comment by pimw1** [comment]
By the way, i'm making some dynamic restfull commands in home assistant so i've a more easy time when creating new automations. For example:

```
rest_command:
    lifx_scene_apply:
    url: 'http://127.0.0.1:6100/v1/lifx/command'
    method: "put"
    payload: |
      {
        "command": "scene_apply",
        "args": {
          "uuid":"{{scene}}",
          "overrides": {
            "duration": {{duration}}
          }
        }
      }
```

In the automation, i'm using the following:
![image](https://user-images.githubusercontent.com/74881023/136666663-ba2f1081-ffc0-4b72-a050-0b4273e45771.png)

Anyhow, i've a question:  is there an override attribute for color temperature (ideally in Kelvin)?

**Comment by pimw1** [comment]
Aah i found it," kelvin"  should work (e.g. value of 3500)

rest_command:
  lifx_scene_apply:
  url: 'http://127.0.0.1:6100/v1/lifx/command'
  method: "put"
  payload: |
    {
      "command": "scene_apply",
      "args": {
        "uuid":"{{scene}}",
        "overrides": {
          "duration": {{duration}},
          "kelvin":{{kelvin}}
        }
      }
    }

**Comment by delfick** [comment]
noice :)

**Comment by pimw1** [comment]
I had quite some stability issues yesterday, despite my rock-solid dedicated 2.4 Ghz network from my Unifi AC Pro. I've quite some devices on my network, so i followed your advice of applying hardcoded discovery in lifx.yaml

```
discovery_options:
  hardcoded_discovery:
    d073d5000001: "192.168.0.1"
    d073d5000002: "192.168.0.2"
```

And the good news is, it works flawlesly since that moment onwards! Happy days.

**Comment by delfick** [comment]
yay, the system works!

Also, this means your router is dropping broadcast traffic (routers are
annoying and can de-prioritise the lights)

My understanding of why they do that is practically non-existent though
hahaha

**Comment by pimw1** [comment]
Yeah i am happy that it works! At the same time, i don't get why Lifx lights are sooo sensitive for these connectivty issues. Literly all my other devices are working 99.9% smoothly, and Lifx only like 90% (which is not enough for a smart bulb). I am glad that Photons Interactor is a good solution for that, well done.

**Comment by delfick** [comment]
I'm sure being a tiny wifi radio in a heat source doesn't help.

But I'm not a hardware or firmware person, so everything I know is a layer
above connectivity problems.

**Comment by pimw1** [comment]
That would be so cool! Is it possible to do the same for other variables, such as kelvin?

**Comment by delfick** [comment]
@pimw1 I've released 0.10.1 with that change.

Any value in overrides when you do a scene_apply will be ignored :)

**Comment by pimw1** [comment]
Awesome!! i'll check it when i'm back from my holidays.

**Comment by delfick** [comment]
nice, enjoy your holiday!
