### ISSUE TITLE
Enhancement request: broadcast Interactor as a Zeroconf service

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#77]
**Dear @delfick:**

This ER exists solely as a reminder to myself that _if_ I actually build that thing we were talking about, _then_ this functionality would be rather useful to have. Until then, I see no reason to spend any more time on it beyond rolling your eyes at it and you've probably already done that. :)

_Yours, &c_
@Djelibeybi

**Comment by delfick** [comment]
mmkay :)

I have no idea what is involved with that, I'll let you figure that out.

**Comment by Djelibeybi** [comment]
It's actually fairly simple and if I could think of a use case for it besides the thing, I'd add it now.

**Comment by Djelibeybi** [comment]
This has been implemented.
