### ISSUE TITLE
The device_finder_info task doesn't return the label for a switch

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#80]
This is because the task uses `GetColor` which the switch declines to handle. Fix incoming.

**Comment by delfick** [comment]
hhahahha, that's funny :)

**Comment by Djelibeybi** [comment]
I'm noodling on an approach via https://github.com/delfick/photons/tree/control/improve-device-finder. Would appreciate any feedback, but no rush. :)

**Comment by Djelibeybi** [comment]
This has been fixed.
